#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
xset r rate 300 50 &
picom --experimental-backends &
xmodmap ~/.config/xmodmap/Xmodmap &
mpd &
mpDris2 &
~/.fehbg &
xfce4-power-manager &
$HOME/.config/polybar/launch.sh
xrdb merge ~/xresources
lxsession &

bspc monitor -d     ﭮ
bspc config border_width        2
bspc config window_gap          4
bspc config split_ratio          0.50

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a telegram-desktop state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#ABE9B3" 
bspc config normal_border_color "#F28FAD"
bspc config active_border_color "#E8A2AF"
bspc config presel_feedback_color "#C9CBFF"

xsetroot -cursor_name left_ptr
wmname LG3D
